### ISSUE TITLE
HIdden The Element[bug] 

### ISSUE THREAD

**Issue by ahmedmohamedrashad01** [hm21/ngx-scroll-animations#1] opened 2024-01-10 01:13 UTC
its not working with angular ssr v17 .  

```html
 <img style="width: 100%; height: 100%;"
  ngxScrollAnimate="fade-in-up"
  easing="ease"
  speed="300"
  delay="0"
  aos="0.8"
  thresholdMode="percent"
  once="true"
  disabled="false"
  src="my source"
  alt="demo-image"
/>
```

hidden the element from the page ,
could you please help me to fix the issue ,
Thanks in advance for your efforts

**Comment by hm21** [comment] 2024-01-10 07:21
Thank you for reporting the issue. I have tested the code with version 17.0.7, both with and without server-side rendering (SSR) and static site generation (SSG), and everything seems to be working fine on my end.

To assist you further, I will need additional information:

1. Please specify the browser you are using, along with its version. Is this issue occurring in multiple browsers such as Chrome, Firefox, Safari, or only in a particular one?

2. Please share the relevant files from your codebase, including `package.json`, `angular.json`, and `main.ts`. If you have files named `app.config.ts` and `app.config.server.ts`, please include those as well.

3. It would be helpful if you could provide a screenshot or a short video (GIF) demonstrating the issue so that I can better understand what exactly is happening.

4. Additionally, if possible, create a minimal StackBlitz example where the issue can be reproduced. This allows me to investigate the problem in a controlled environment.


Btw, did you import the file with the prebuilt animations like the example below, or did you create your own custom animation?

```css
/* angular-cli file: src/styles.css */
@import "node_modules/ngx-scroll-animations/styles/animations.min.css";
```

If you have implemented your own custom animations, they should look like this:
```css
@keyframes fade-in-up {
    from {
        opacity: 0;
        transform: translateY(60px);
    }
    to {
        opacity: 1;
        transform: translateY(0);
    }
}
```

**Comment by ahmedmohamedrashad01** [comment] 2024-01-11 14:57
Thanks for your efforts and support , 
The animation now is working with first image only of the page, The other elments got hidden from the page , and its working with image only ( first image of the page ) not other HTML tags like div, p, section etc ..., 
this is style.css @import "../node_modules/ngx-scroll-animations/styles/animations.min.css";
i tried to put the like without ../ but was not working.

 package.json
```json
{
  "name": "ahmed-rashad",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/cdk": "^17.0.1",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/material": "^17.0.1",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/platform-server": "^17.0.0",
    "@angular/router": "^17.0.0",
    "@angular/ssr": "^17.0.0",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "@types/gsap": "^3.0.0",
    "animate.css": "^4.1.1",
    "aos": "^2.3.4",
    "bootstrap": "^5.3.2",
    "express": "^4.18.2",
    "gsap": "^3.12.4",
    "i18n": "^0.15.1",
    "ng-animate": "^2.0.1",
    "ngx-cookie-service": "^17.0.0",
    "ngx-image-zoom": "^3.0.0",
    "ngx-scroll-animations": "^1.0.8",
    "ngx-spinner": "^16.0.2",
    "ngx-toastr": "^18.0.0",
    "rxjs": "~7.8.0",
    "swiper": "^11.0.5",
    "tslib": "^2.3.0",
    "uuidv4": "^6.2.13",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.0",
    "@angular/cli": "^17.0.0",
    "@angular/compiler-cli": "^17.0.0",
    "@types/aos": "^3.0.7",
    "@types/express": "^4.17.17",
    "@types/jasmine": "~5.1.0",
    "@types/node": "^18.18.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  }
}
```

Angular.json 
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ahmed_rashad": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "standalone": false
        },
        "@schematics/angular:directive": {
          "standalone": false
        },
        "@schematics/angular:pipe": {
          "standalone": false
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/ahmed_rashad",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": ["zone.js"],
            "tsConfig": "tsconfig.app.json",
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "@angular/material/prebuilt-themes/indigo-pink.css",

              "node_modules/ngx-spinner/animations/square-jelly-box.css",
              "node_modules/ngx-spinner/animations/ball-climbing-dot.css",
              "node_modules/ngx-spinner/animations/pacman.css",
              "node_modules/ngx-spinner/animations/ball-scale-multiple.css",
              "node_modules/ngx-toastr/toastr.css",

              "node_modules/swiper/swiper-bundle.css",

              "node_modules/animate.css/animate.min.css",

              "node_modules/aos/dist/aos.css",

              

              "src/styles.css"
            ],
            "scripts": [
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
              "node_modules/swiper/swiper-bundle.js",
              "node_modules/aos/dist/aos.js"
            ],
            "server": "src/main.server.ts",
            "prerender": true,
            "ssr": {
              "entry": "server.ts"
            }
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2mb",
                  "maximumError": "2mb"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "ahmed_rashad:build:production"
            },
            "development": {
              "buildTarget": "ahmed_rashad:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "ahmed_rashad:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": ["zone.js", "zone.js/testing"],
            "tsConfig": "tsconfig.spec.json",
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": [
              "@angular/material/prebuilt-themes/indigo-pink.css",
              "src/styles.css"
            ],
            "scripts": []
          }
        }
      }
    }
  }
}
```

main.ts
```typescript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.error(err));
```
main.server.ts
```typescript
export { AppServerModule as default } from './app/app.module.server';
```

**Comment by ahmedmohamedrashad01** [comment] 2024-01-11 15:02
I Tried with section but its working only with first section of the page, the other elements below the first element got hidden from the page ( working only with first element )
![ngx_scroll_animation](https://github.com/hm21/ngx-scroll-animations/assets/96224285/d5d71f3a-72ca-404e-96a4-f0d83b03d801)

**Comment by hm21** [comment] 2024-01-11 16:39
Thank you for showing me a bit of your code. In this case, it seems that the CSS animation should not make any issues. Btw, I noticed that you are using animate.css. I recommend using the animations directly from this package and not including the pre-built animations, so you don't have redundant code. For example, you can use the `fadeInUp` animation from animate.css without the "animate__" prefix like this:

```html
<section ngxScrollAnimate="fadeInUp">
   <!-- Your content -->
</section>
```

Now, let's address the problem. Based on how you've described the issue and what I see in your code, it appears to be related to the service that manages all scroll events. This service listens to scroll events on the window as follows:

```typescript
  constructor(
    private zone: NgZone,
    @Inject(DOCUMENT) private document: Document,
    @Inject(PLATFORM_ID) private platformId: any,
  ) {
    if (isPlatformBrowser(this.platformId)) {
      // Observable for scroll events on the window
      this.scroll$ = fromEvent(this.document, 'scroll').pipe(
        throttleTime(50, undefined, { leading: true, trailing: true }),
        share(),
      );
    }
  }
```

If only the first section is triggered, the observable will not detect any more scroll events and will initiate all animations that are currently in the viewport at the top position.

Now, I have a few questions:

- Does the content you are scrolling have a scrollbar that is different from the browser's default scrollbar?
- Are you using any libraries that modify the scroll behavior? I noticed you're using `gsap`, which seems to interact with the scrollbar, but I haven't worked with it, so I'm not certain. If you use this package as a parent element, consider removing it temporarily to see if the issue persists.
- It's also possible that the issue might be specific to your browser. Could you please let me know the name and version of your browser? This will help determine if it's a browser-specific problem, especially if it's not one of the two latest versions of Chrome, Firefox, Opera, or Safari.


As a test, could you please perform the following steps in your environment to confirm whether the issue is related to the scroll-observable:

1. Copy and paste the following code into your `app.component.html` and comment out all of your existing code:
```html
@for (example of examples; let exampleIndex = $index; track exampleIndex) {
<section>
  <h1 [innerText]="example.title"></h1>

  <div class="grid">
    @for (item of items; let i = $index; track i) {
    <img
      [ngxScrollAnimate]="
        example.animationType ? example.animationType[i] : 'fade-in-up'
      "
      [speed]="
        example.differentSpeed ? example.speed! * (i + 1) : example.speed
      "
      [delay]="example.delay ?? 0"
      [aos]="example.threshold"
      [thresholdMode]="example.thresholdMode"
      [easing]="example.easing ? example.easing[i] : 'ease'"
      [disabled]="example.disabled"
      [once]="example.once ?? true"
      src="https://picsum.photos/id/{{
        150 + (i + 1) * (exampleIndex + 1)
      }}/300"
      alt="demo-image"
    />
    }
  </div>
</section>
}
```
2. Do the same with your `app.component.ts` with this code:
```typescript
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { NgxScrollAnimationsModule, ThresholdModeT } from 'ngx-scroll-animations';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  imports: [NgxScrollAnimationsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {

  public examples: ItemI[] = [
    {
      title: 'Disable animations',
      disabled: true,
    },
    {
      title: 'Delay 1000ms',
      delay: 1_000,
      speed: 500,
    },
    {
      title: 'Easing options',
      speed: 1_000,
      threshold: 0.8,
      easing: [
        'ease',
        'ease-out',
        'ease-in',
        'ease-in-out',
        'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      ],
    },
    {
      title: 'Threshold 20px',
      threshold: 20,
      thresholdMode: 'pixel',
    },
    {
      title: 'Threshold 60%',
      threshold: 0.6,
      thresholdMode: 'percent',
    },
    {
      title: 'Different speed',
      differentSpeed: true,
      speed: 500,
      threshold: 0.7,
      thresholdMode: 'percent',
    },
    {
      title: 'Multiple animate',
      speed: 500,
      threshold: 0.7,
      once: false,
    },
    {
      title: 'Custom animations',
      speed: 1_200,
      threshold: 1,
      once: false,
      animationType: [
        'fade-in-right',
        'fade-in',
        'slide-in-up',
        'fade-in-up-scale',
        'fade-in-left',
      ],
    },
  ];

  public items = new Array(5);
}


interface ItemI {
  title: string;
  differentSpeed?: boolean;
  disabled?: boolean;
  once?: boolean;
  thresholdMode?: ThresholdModeT;
  threshold?: number;
  speed?: number;
  delay?: number;
  easing?: string[];
  animationType?: string[];
}
```

3. And also with your `app.component.css`:
```css
 
h1 {
    font-size: 1.4rem;
    font-weight: 600;
    margin: 0;
    padding: 0px;
}

.grid {
    display: grid;
    width: 100%;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 10px;
    margin-bottom: 80px;
}

img {
    width: 100%;
    min-height:250px;
    background-color: aqua;
    height: auto;
    box-sizing: border-box;
    object-fit: cover;
    border-radius: 4px;
}
```

**Comment by ahmedmohamedrashad01** [comment] 2024-01-11 17:14
Thanks for your efforts, I wrote the same code and still the same issue only first element is appearing in the page and the other elements are hidden 
![ngx 1](https://github.com/hm21/ngx-scroll-animations/assets/96224285/f706ef96-2b0c-48c6-b33c-82e320bdf799)
![ngx 2](https://github.com/hm21/ngx-scroll-animations/assets/96224285/d5dece8e-3640-498f-9346-fbfe894b55f9)

**Comment by hm21** [comment] 2024-01-11 17:21
Okay, just to confirm, did you make sure to comment out all other code in your `app.component` and insert my example? I noticed in your screenshots that there's still a navigation bar and the Chat-button, which should not be visible anymore if the test is done correctly. Additionally, could you please let me know the name and version of your current web browser?

**Comment by ahmedmohamedrashad01** [comment] 2024-01-11 17:24
i wrote all of your code and display everything but animation not working only first element other elements are hidden , i used the code inside home.component

**Comment by hm21** [comment] 2024-01-11 18:02
It's essential to put the code inside `app.component` and not another component like `home.component`. Can you please try it in `app.component` and give me feedback?

**Comment by ahmedmohamedrashad01** [comment] 2024-01-11 18:39
Now put the code in app.component.ts
```typescript
import {
  Component,
  Inject,
  NgZone,
  OnInit,
  PLATFORM_ID,
  inject,
  ChangeDetectionStrategy
} from '@angular/core';


import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { fromEvent, share, throttleTime } from 'rxjs';
import { ThresholdModeT } from 'ngx-scroll-animations';

interface ItemI {
  title: string;
  differentSpeed?: boolean;
  disabled?: boolean;
  once?: boolean;
  thresholdMode?: ThresholdModeT;
  threshold?: number;
  speed?: number;
  delay?: number;
  easing?: string[];
  animationType?: string[];
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  scroll$
  constructor(

    private zone: NgZone,
    @Inject(DOCUMENT) private document: Document,
    @Inject(PLATFORM_ID) private platformId: any,
    
  ) {

    if (isPlatformBrowser(this.platformId)) {
      // Observable for scroll events on the window
      this.scroll$ = fromEvent(this.document, 'scroll').pipe(
        throttleTime(50, undefined, { leading: true, trailing: true }),
        share(),
      );
    }
  }

  ngOnInit(): void {
  }
  // ___________________

  public examples: ItemI[] = [
    {
      title: 'Disable animations',
      disabled: true,
    },
    {
      title: 'Delay 1000ms',
      delay: 1_000,
      speed: 500,
    },
    {
      title: 'Easing options',
      speed: 1_000,
      threshold: 0.8,
      easing: [
        'ease',
        'ease-out',
        'ease-in',
        'ease-in-out',
        'cubic-bezier(0.175, 0.885, 0.32, 1.275)',
      ],
    },
    {
      title: 'Threshold 20px',
      threshold: 20,
      thresholdMode: 'pixel',
    },
    {
      title: 'Threshold 60%',
      threshold: 0.6,
      thresholdMode: 'percent',
    },
    {
      title: 'Different speed',
      differentSpeed: true,
      speed: 500,
      threshold: 0.7,
      thresholdMode: 'percent',
    },
    {
      title: 'Multiple animate',
      speed: 500,
      threshold: 0.7,
      once: false,
    },
    {
      title: 'Custom animations',
      speed: 1_200,
      threshold: 1,
      once: false,
      animationType: [
        'fade-in-right',
        'fade-in',
        'slide-in-up',
        'fade-in-up-scale',
        'fade-in-left',
      ],
    },
  ];
  public items = new Array(5);
}
```
app.modules.ts
```typescript
import { NgxScrollAnimationsModule} from 'ngx-scroll-animations';


@NgModule({
  declarations: [AppComponent, ClickOutsideDirective, HomeComponent, ContinueHomeComponent, NavComponent],
  providers: [provideClientHydration(), provideHttpClient(withFetch())],
  bootstrap: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule, 
    NgxScrollAnimationsModule,
  ],
  
})
export class AppModule {}
```

APP.component.html
```html
@for (example of examples; let exampleIndex = $index; track exampleIndex) {
  <section>
    <h1 [innerText]="example.title"></h1>
  
    <div class="grid">
      @for (item of items; let i = $index; track i) {
      <img
        [ngxScrollAnimate]="
          example.animationType ? example.animationType[i] : 'fade-in-up'
        "
        [speed]="
          example.differentSpeed ? example.speed! * (i + 1) : example.speed
        "
        [delay]="example.delay ?? 0"
        [aos]="example.threshold"
        [thresholdMode]="example.thresholdMode"
        [easing]="example.easing ? example.easing[i] : 'ease'"
        [disabled]="example.disabled"
        [once]="example.once ?? true"
        src="https://picsum.photos/id/{{
          150 + (i + 1) * (exampleIndex + 1)
        }}/300"
        alt="demo-image"
      />
      }
    </div>
  </section>
  }
```

 app.component.css
```css
  /* animation */
   
h1 {
  font-size: 1.4rem;
  font-weight: 600;
  margin: 0;
  padding: 0px;
}

.grid {
  display: grid;
  width: 100%;
  grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
  gap: 10px;
  margin-bottom: 80px;
}

img {
  width: 100%;
  min-height:250px;
  background-color: aqua;
  height: auto;
  box-sizing: border-box;
  object-fit: cover;
  border-radius: 4px;
}
```
still not working and even scroll animation not working with the first element and hide the other elements
![1](https://github.com/hm21/ngx-scroll-animations/assets/96224285/23a4049f-fe10-4712-8294-abf5cb1db5f3)
![2](https://github.com/hm21/ngx-scroll-animations/assets/96224285/155c126a-7bf7-4377-b3d3-2c0f8822da6f)
![3](https://github.com/hm21/ngx-scroll-animations/assets/96224285/10053f39-4534-49d2-b8f8-eb126a03b8c7)
![4](https://github.com/hm21/ngx-scroll-animations/assets/96224285/24c6b71f-4cd3-4e18-8751-44f2fa72bf12)
![5](https://github.com/hm21/ngx-scroll-animations/assets/96224285/1527012a-e157-424d-a9fd-068d522e67ab)

**Comment by hm21** [comment] 2024-01-11 18:57
Thank you for testing within your `app.component`. However, I'm curious about the presence of the chat button. Is that button dynamically inserted into your DOM using a script? Would it be possible for me to take a look at your `index.html` file? There might be an issue there.

I've also noticed that your scrollbar doesn't resemble a native scrollbar. Is it styled purely using CSS, or are you using a package or tool that modifies its appearance and behavior? I'm asking because some packages can alter the scrollbar and its functionality in a way that scroll events may not work correctly anymore.

And can you change in the code which i sent you also the app.component.html to this:
```html
@for (example of examples; let exampleIndex = $index; track exampleIndex) {
  <section>
    <h1 [innerText]="example.title"></h1>
  
    <div class="grid">
      @for (item of items; let i = $index; track i) {
      <img
        [ngxScrollAnimate]="
          example.animationType ? example.animationType[i] : 'fadeInUp'
        "
        [speed]="
          example.differentSpeed ? example.speed! * (i + 1) : example.speed
        "
        [delay]="example.delay ?? 0"
        [aos]="example.threshold"
        [thresholdMode]="example.thresholdMode"
        [easing]="example.easing ? example.easing[i] : 'ease'"
        [disabled]="example.disabled"
        [once]="example.once ?? true"
        src="https://picsum.photos/id/{{
          150 + (i + 1) * (exampleIndex + 1)
        }}/300"
        alt="demo-image"
      />
      }
    </div>
  </section>
  }
```

**Comment by ahmedmohamedrashad01** [comment] 2024-01-16 09:10
Thanks for reply,
The button has position also changed the scroll to default , The library is working fine but with angular without SSR, the problem if the app has SSR all the animations libs does not working 
i tried a lot of libraries like (ngx-scroll-animations, AOS , Gsap ) and still same issue I think the main cause of the problem is SSR and also without SSR no SEO 😓

**Comment by hm21** [comment] 2024-01-16 10:41
Don't worry, it's definitely possible to use animations even you use SSR. The important is just that the animations are triggered on the client side and on the server side we just make them invisible (opacity: 0). In my opinion, is something not correct in your code that my and other scroll-animation-packages not working. 

However, if you want that I can try to find the error in your code, will it help when you create a [StackBlitz](https://stackblitz.com/) where the error happens.

The other option is that I try to reproduce it with the code you already sent me. For that, I also need to see your `app.server.module.ts`.

Btw in your code which you show me before you declare it like this in your `main.server.ts`:
```typescript
export { AppServerModule as default } from './app/app.module.server';
```
This appears to be incorrect to me. Could you please share the contents of your `app.server.module.ts` and `app.module.server` files so that I can better assist you in resolving this issue?

FYI Angular version 17, have been some changes in how SSR is handled. While the older code with modules will still work, I recommend you to read more about the new official way in the Angular documentation [here](https://angular.dev/guide/ssr#enable-server-side-rendering).

**Comment by ahmedmohamedrashad01** [comment] 2024-01-16 20:05
Thanks for your support and efforts,
on StackBlitz it will working fine same like other libraries because no SSR on StackBlitz,
This is app.module.server.ts :
```typescript
import { NgModule } from '@angular/core';
import { ServerModule } from '@angular/platform-server';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';

@NgModule({
  imports: [
    AppModule,
    ServerModule,
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule {}
```
main.server.ts : 
```typescript
export { AppServerModule as default } from './app/app.module.server';
```
its already declared when i created the angular app and i did not change anything in thid file 
______________________________________________________________
i have only app.module.server but i did not have app.server.module.ts file,

**Comment by ahmedmohamedrashad01** [comment] 2024-01-16 20:16
still working with first element of the page and the other elements got hidden,
![image](https://github.com/hm21/ngx-scroll-animations/assets/96224285/9f27a89c-b3b1-4175-be43-7eaf3a30d81a)

**Comment by ahmedmohamedrashad01** [comment] 2024-01-16 20:40
This is server.ts file ,
```typescript
import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/ssr';
import express from 'express';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import AppServerModule from './src/main.server';



// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');
  const indexHtml = join(serverDistFolder, 'index.server.html');

  const commonEngine = new CommonEngine();

  server.set('view engine', 'html');
  server.set('views', browserDistFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(browserDistFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Angular engine
  server.get('*', (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    commonEngine
      .render({
        bootstrap: AppServerModule,
        documentFilePath: indexHtml,
        url: `${protocol}://${headers.host}${originalUrl}`,
        publicPath: browserDistFolder,
        providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
      })
      .then((html) => res.send(html))
      .catch((err) => next(err));
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

run();
```

**Comment by hm21** [comment] 2024-01-16 21:56
Thank you for sharing the code. It's correct in StackBlitz, although SSR won't work there, it does make it easier for me to copy your code to my machine for testing. However, I've already copied all of your code and tried it out. The good news is that your code is correct and should work. The bad news is that even though I've configured everything the same as you did, it still works perfectly fine with SSR enabled.

I now suspect that the issue may be related to the animation not loading or starting. Could you please check the browser dev console to see if the styles of an element with animation look like below?

```html
style="opacity: 0; animation: 1000ms ease-out 0s 1 normal none running fade-in-up;"
```

Or like in the image below:

<img src="https://github.com/hm21/ngx-scroll-animations/assets/40503456/9bf63b09-abf4-43dc-ac4c-4a14a9cf5e4a" width="300">


When the animation is not loaded, you will always have this part in the style. However, if the animation is loaded, this part will be removed.

Could you also try adding the animations to angular.json directly as shown below to see if it helps?
```json
"styles": [
    "node_modules/bootstrap/dist/css/bootstrap.min.css",
    "@angular/material/prebuilt-themes/indigo-pink.css",
    "node_modules/ngx-spinner/animations/square-jelly-box.css",
    "node_modules/ngx-spinner/animations/ball-climbing-dot.css",
    "node_modules/ngx-spinner/animations/pacman.css",
    "node_modules/ngx-spinner/animations/ball-scale-multiple.css",
    "node_modules/ngx-toastr/toastr.css",
    "node_modules/swiper/swiper-bundle.css",
    "node_modules/animate.css/animate.min.css",
    "node_modules/aos/dist/aos.css",
    "src/styles.css",
    "node_modules/ngx-scroll-animations/styles/animations.min.css"
  ],
```

When testing it with SSR, do you encounter this issue exclusively on your server, or does it also pose problems when serving it locally with SSR?

Additionally, please verify if the animation appears in your `style.css`, which you can check in the network tab as shown below:


<img src="https://github.com/hm21/ngx-scroll-animations/assets/40503456/a206d135-4a85-4259-89fe-0cec30965416" width="400">

**Comment by ahmedmohamedrashad01** [comment] 2024-01-16 22:25
Thanks for your efforts ,
I have been changed the style array in angular.json file ,
    "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "@angular/material/prebuilt-themes/indigo-pink.css",
              "node_modules/ngx-spinner/animations/square-jelly-box.css",
              "node_modules/ngx-spinner/animations/ball-climbing-dot.css",
              "node_modules/ngx-spinner/animations/pacman.css",
              "node_modules/ngx-spinner/animations/ball-scale-multiple.css",
              "node_modules/ngx-toastr/toastr.css",
              "node_modules/swiper/swiper-bundle.css",
              "node_modules/animate.css/animate.min.css",
              "node_modules/aos/dist/aos.css",
              "src/styles.css",
              "node_modules/ngx-scroll-animations/styles/animations.min.css"
            ],
and checked the element on the browser , the first element already showing and animation working but the second element and the others below elements has opacity 0 
![opacity](https://github.com/hm21/ngx-scroll-animations/assets/96224285/02acdb7e-a4fa-460c-92ea-94d33d58fdd4)
and when i run the SSR app its working fine without any issue , 
![jh](https://github.com/hm21/ngx-scroll-animations/assets/96224285/b8c2f2a0-db62-4981-9325-95ad91a54972)

**Comment by ahmedmohamedrashad01** [comment] 2024-01-17 00:03
Thank you so much and thanks for your efforts ,
i find the problem , my current angular app is without standalone so all the animation are not working ,
but i created now a new standalone app and animation is working fine ,
Thanks and I am sorry for the disturb .

**Comment by ahmedmohamedrashad01** [comment] 2024-01-17 06:34
The Problem has been solved ,
Thank you

**Comment by ahmedmohamedrashad01** [comment] 2024-01-17 08:53
I found the basic problem through which any scroll animation library does not work in angualr
I thought that was the problem
because i was using angular without standalone and I copied the codes from my app to standalone app again the issue happened when i copied the old css style from style.css 
i find property overflow_x hidden it was the one causing the problem

**Comment by ahmedmohamedrashad01** [comment] 2024-01-17 08:56
I found the basic problem through which any scroll animation library does not work in angualr
I thought that was the problem
because i was using angular without standalone and I copied the codes from my app to standalone app again the issue happened when i copied the old css style from style.css
i find property overflow_x hidden it was the one causing the problem

**Comment by hm21** [comment] 2024-01-17 09:32
Exactly, standalone is not necessary that the animations will work. 
It's also important that we use the `document` scrollbar and not force it to create an element scrollbar on a child element, like it will happen when you set overflow to hidden. That was the reason I ask you [here](https://github.com/hm21/ngx-scroll-animations/issues/1#issuecomment-1887547202) if you sure that you use the document scrollbar. But I forgot to tell you in the test example that you should remove all styles in `angular.json` what was the reason that the issue continues to occur.

However, I know in some cases is it required that we have on a child element a scrollbar. But in the most scroll-animation packages like my one, we set the observable in a service to the `document` which will have the best performance and is for the most users enough. For the case you need to set `overflow` to hidden, I recommend you to copy my code and just change in the service the part below. That should work with every element which has a scrollbar.

```typescript
  constructor(
    private zone: NgZone,
    @Inject(DOCUMENT) private document: Document,
    @Inject(PLATFORM_ID) private platformId: any,
  ) {
    if (isPlatformBrowser(this.platformId)) {
      this.scroll$ = fromEvent(/* Use the element-ref from the element with the scrollbar */, 'scroll').pipe(
        throttleTime(50, undefined, { leading: true, trailing: true }),
        share(),
      );
    }
  }
```

**Closed as completed** 2024-01-18 21:30 UTC
Labels: bug
